// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_cookie_login_auth_login_post = {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
};

export type Body_reset_forgot_password_auth_forgot_password_post = {
	email: string;
};

export type Body_reset_reset_password_auth_reset_password_post = {
	token: string;
	password: string;
};

export type Body_upload_milestone_group_image_admin_milestone_group_images__milestone_group_id__put =
	{
		file: Blob | File;
	};

export type Body_upload_milestone_image_admin_milestone_images__milestone_id__post = {
	file: Blob | File;
};

export type Body_verify_request_token_auth_request_verify_token_post = {
	email: string;
};

export type Body_verify_verify_auth_verify_post = {
	token: string;
};

export type ErrorModel = {
	detail:
		| string
		| {
				[key: string]: string;
		  };
};

export type HTTPValidationError = {
	detail?: Array<ValidationError>;
};

export type Language = {
	id?: number | null;
	lang: string;
};

export type LanguageCreate = {
	lang: string;
};

export type MilestoneAdmin = {
	id: number;
	group_id: number;
	order: number;
	text?: {
		[key: string]: MilestoneText;
	};
	images?: Array<MilestoneImage>;
};

export type MilestoneGroupAdmin_Input = {
	id: number;
	order: number;
	text?: {
		[key: string]: MilestoneGroupText;
	};
	milestones?: Array<MilestoneAdmin>;
};

export type MilestoneGroupAdmin_Output = {
	id: number;
	order: number;
	text?: {
		[key: string]: MilestoneGroupText;
	};
	milestones?: Array<MilestoneAdmin>;
};

export type MilestoneGroupPublic = {
	id: number;
	text?: {
		[key: string]: MilestoneGroupTextPublic;
	};
	milestones?: Array<MilestonePublic>;
};

export type MilestoneGroupText = {
	title?: string;
	desc?: string;
	group_id?: number | null;
	lang_id?: number | null;
};

export type MilestoneGroupTextPublic = {
	title?: string;
	desc?: string;
};

export type MilestoneImage = {
	id?: number | null;
	milestone_id?: number | null;
	filename?: string;
	approved?: boolean;
};

export type MilestoneImagePublic = {
	filename: string;
	approved: boolean;
};

export type MilestonePublic = {
	id: number;
	text?: {
		[key: string]: MilestoneGroupTextPublic;
	};
	images?: Array<MilestoneImagePublic>;
};

export type MilestoneText = {
	title?: string;
	desc?: string;
	obs?: string;
	help?: string;
	milestone_id?: number | null;
	lang_id?: number | null;
};

export type UserCreate = {
	email: string;
	password: string;
	is_active?: boolean | null;
	is_superuser?: boolean | null;
	is_verified?: boolean | null;
	is_researcher?: boolean | null;
};

export type UserRead = {
	id: number;
	email: string;
	is_active?: boolean;
	is_superuser?: boolean;
	is_verified?: boolean;
	is_researcher: boolean;
};

export type UserUpdate = {
	password?: string | null;
	email?: string | null;
	is_active?: boolean | null;
	is_superuser?: boolean | null;
	is_verified?: boolean | null;
	is_researcher?: boolean | null;
};

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type GetLanguagesLanguagesGetResponse = {
	[key: string]: string;
};

export type GetLanguagesLanguagesGetError = unknown;

export type GetMilestonesMilestonesGetResponse = Array<MilestonePublic>;

export type GetMilestonesMilestonesGetError = unknown;

export type GetMilestoneMilestonesMilestoneIdGetData = {
	path: {
		milestone_id: number;
	};
};

export type GetMilestoneMilestonesMilestoneIdGetResponse = MilestonePublic;

export type GetMilestoneMilestonesMilestoneIdGetError = HTTPValidationError;

export type GetMilestoneGroupsMilestoneGroupsGetResponse = Array<MilestoneGroupPublic>;

export type GetMilestoneGroupsMilestoneGroupsGetError = unknown;

export type GetMilestoneGroupMilestoneGroupsMilestoneGroupIdGetData = {
	path: {
		milestone_group_id: number;
	};
};

export type GetMilestoneGroupMilestoneGroupsMilestoneGroupIdGetResponse = MilestoneGroupPublic;

export type GetMilestoneGroupMilestoneGroupsMilestoneGroupIdGetError = HTTPValidationError;

export type CreateLanguageAdminLanguagesPostData = {
	body: LanguageCreate;
};

export type CreateLanguageAdminLanguagesPostResponse = Language;

export type CreateLanguageAdminLanguagesPostError = HTTPValidationError;

export type DeleteLanguageAdminLanguagesLanguageIdDeleteData = {
	path: {
		language_id: number;
	};
};

export type DeleteLanguageAdminLanguagesLanguageIdDeleteResponse = Language;

export type DeleteLanguageAdminLanguagesLanguageIdDeleteError = HTTPValidationError;

export type GetMilestoneGroupsAdminMilestoneGroupsGetResponse = Array<MilestoneGroupAdmin_Output>;

export type GetMilestoneGroupsAdminMilestoneGroupsGetError = unknown;

export type CreateMilestoneGroupAdminMilestoneGroupsPostResponse = MilestoneGroupAdmin_Output;

export type CreateMilestoneGroupAdminMilestoneGroupsPostError = unknown;

export type UpdateMilestoneGroupAdminMilestoneGroupsPutData = {
	body: MilestoneGroupAdmin_Input;
};

export type UpdateMilestoneGroupAdminMilestoneGroupsPutResponse = MilestoneGroupAdmin_Output;

export type UpdateMilestoneGroupAdminMilestoneGroupsPutError = HTTPValidationError;

export type DeleteMilestoneGroupAdminMilestoneGroupsMilestoneGroupIdDeleteData = {
	path: {
		milestone_group_id: number;
	};
};

export type DeleteMilestoneGroupAdminMilestoneGroupsMilestoneGroupIdDeleteResponse = unknown;

export type DeleteMilestoneGroupAdminMilestoneGroupsMilestoneGroupIdDeleteError =
	HTTPValidationError;

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutData = {
	body: Body_upload_milestone_group_image_admin_milestone_group_images__milestone_group_id__put;
	path: {
		milestone_group_id: number;
	};
};

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutResponse = unknown;

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutError =
	HTTPValidationError;

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostData = {
	path: {
		milestone_group_id: number;
	};
};

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostResponse = MilestoneAdmin;

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostError = HTTPValidationError;

export type UpdateMilestoneAdminMilestonesPutData = {
	body: MilestoneAdmin;
};

export type UpdateMilestoneAdminMilestonesPutResponse = MilestoneAdmin;

export type UpdateMilestoneAdminMilestonesPutError = HTTPValidationError;

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteData = {
	path: {
		milestone_id: number;
	};
};

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteResponse = unknown;

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteError = HTTPValidationError;

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostData = {
	body: Body_upload_milestone_image_admin_milestone_images__milestone_id__post;
	path: {
		milestone_id: number;
	};
};

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostResponse = MilestoneImage;

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostError = HTTPValidationError;

export type UsersCurrentUserUsersMeGetResponse = UserRead;

export type UsersCurrentUserUsersMeGetError = unknown;

export type UsersPatchCurrentUserUsersMePatchData = {
	body: UserUpdate;
};

export type UsersPatchCurrentUserUsersMePatchResponse = UserRead;

export type UsersPatchCurrentUserUsersMePatchError = ErrorModel | unknown | HTTPValidationError;

export type UsersUserUsersIdGetData = {
	path: {
		id: string;
	};
};

export type UsersUserUsersIdGetResponse = UserRead;

export type UsersUserUsersIdGetError = unknown | HTTPValidationError;

export type UsersPatchUserUsersIdPatchData = {
	body: UserUpdate;
	path: {
		id: string;
	};
};

export type UsersPatchUserUsersIdPatchResponse = UserRead;

export type UsersPatchUserUsersIdPatchError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserUsersIdDeleteData = {
	path: {
		id: string;
	};
};

export type UsersDeleteUserUsersIdDeleteResponse = void;

export type UsersDeleteUserUsersIdDeleteError = unknown | HTTPValidationError;

export type AuthCookieLoginAuthLoginPostData = {
	body: Body_auth_cookie_login_auth_login_post;
};

export type AuthCookieLoginAuthLoginPostResponse = unknown | void;

export type AuthCookieLoginAuthLoginPostError = ErrorModel | HTTPValidationError;

export type AuthCookieLogoutAuthLogoutPostResponse = unknown | void;

export type AuthCookieLogoutAuthLogoutPostError = unknown;

export type RegisterRegisterAuthRegisterPostData = {
	body: UserCreate;
};

export type RegisterRegisterAuthRegisterPostResponse = UserRead;

export type RegisterRegisterAuthRegisterPostError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordAuthForgotPasswordPostData = {
	body: Body_reset_forgot_password_auth_forgot_password_post;
};

export type ResetForgotPasswordAuthForgotPasswordPostResponse = unknown;

export type ResetForgotPasswordAuthForgotPasswordPostError = HTTPValidationError;

export type ResetResetPasswordAuthResetPasswordPostData = {
	body: Body_reset_reset_password_auth_reset_password_post;
};

export type ResetResetPasswordAuthResetPasswordPostResponse = unknown;

export type ResetResetPasswordAuthResetPasswordPostError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenAuthRequestVerifyTokenPostData = {
	body: Body_verify_request_token_auth_request_verify_token_post;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostResponse = unknown;

export type VerifyRequestTokenAuthRequestVerifyTokenPostError = HTTPValidationError;

export type VerifyVerifyAuthVerifyPostData = {
	body: Body_verify_verify_auth_verify_post;
};

export type VerifyVerifyAuthVerifyPostResponse = UserRead;

export type VerifyVerifyAuthVerifyPostError = ErrorModel | HTTPValidationError;

export type AuthResearchAuthGetResponse = unknown;

export type AuthResearchAuthGetError = unknown;
